### ISSUE TITLE
Throws an exception

### ISSUE THREAD

**Issue by johannesjo** [rembound/Arena-Helper#133]
V0.8.7
```
Make sure you are using the latest version of the Plugin and HDT.

System.NullReferenceException: Object reference not set to an instance of an object.
   at ArenaHelper.Plugin.<CheckDataUpdate>d__1a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ArenaHelper.Plugin.<CheckUpdate>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by allenyin55** [comment]
Any updates on this? I am having the same problem.

**Comment by rembound** [comment]
Looks like something goes wrong, sometimes, when trying to update the data. Make sure the plugin and HDT are correctly installed.

You can try re-installing or cleaning the `%AppData%\HearthstoneDeckTracker\ArenaHelper` directory.
