### ISSUE TITLE
Plugins not showing up in HDT

### ISSUE THREAD

**Issue by Grandorx** [rembound/Arena-Helper#163]
Plugins worked fine before, but since updating to 1.11.2 the Plugins section in Options is empty, despite the plugins being present in the Plugins folder.

Plugins are present in the /roaming/ tree and seem to be copied correctly to /local/.

Log errors:
`1:02:07 PM|Info|PluginManager.LoadPluginsFromPath >> Loading Plugins...
1:02:07 PM|Error|PluginManager.GetModule >> Error loading C:\Users\XXX\AppData\Local\HearthstoneDeckTracker\app-1.11.2\Plugins\PackTracker.dll:
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Hearthstone_Deck_Tracker.Plugins.PluginManager.GetModule(String pFileName, Type pTypeInterface) in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Plugins\PluginManager.cs:line 196
1:02:07 PM|Error|PluginManager.GetModule >> Error loading C:\Users\XXX\AppData\Local\HearthstoneDeckTracker\app-1.11.2\Plugins\ArenaHelper\ArenaHelper.dll:
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Hearthstone_Deck_Tracker.Plugins.PluginManager.GetModule(String pFileName, Type pTypeInterface) in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Plugins\PluginManager.cs:line 196
1:02:07 PM|Info|Helper.GetCurrentRegion >> Region: EU`

![image](https://user-images.githubusercontent.com/27730328/80597052-379ee180-8a1f-11ea-9e4b-7dca34182c33.png)

**Comment by Grandorx** [comment]
Apologies - raised in the wrong project.
