### ISSUE TITLE
Everytime I try opening arena helper it crashes HDT

### ISSUE THREAD

**Issue by lkenzou** [rembound/Arena-Helper#33]
###### #### 21/09/2015 20:22:32

System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em ArenaHelper.Plugin.LoadArenaData(String filename)
   em ArenaHelper.Plugin.InitializeMainWindow()
   em ArenaHelper.Plugin.ActivateArenaWindow()
   em ArenaHelper.Plugin.<AddMenuItem>b__1(Object sender, RoutedEventArgs args)
   em System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   em System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   em System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   em System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   em System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[20:22:15] Game: -------- Reset ---------
[20:22:15] OpponentSecrets: Cleared secrets
[20:22:15] DeckList: Set active deck to: Arena 18-09 10:53 (Mage)
[20:22:16] Tracker: Switched to deck: Arena 18-09 10:53
[20:22:16] Game: -------- Reset ---------
[20:22:16] OpponentSecrets: Cleared secrets
[20:22:16] GameEventHandler: Reset constructed importing
[20:22:17] Helper: Checking for LIVE updates...
[20:22:17] Helper: Current version: 0.11.3.0
[20:22:17] LogReader: Current region: US
[20:22:17] UpdateOverlay: Refreshed overlay topmost status
[20:22:17] BackupManager: Running BackupManager
[20:22:17] BackupManager: Backup for today already exists
[20:22:17] PluginManager: Loading Plugins...
[20:22:18] : Checking for duplicate matches...
[20:22:18] Game: set CurrentGameMode to Arena
[20:22:18] : Created new arena deck: Mage
[20:22:18] : Added new card to arena deck: AT_006 (1/30)
[20:22:18] : Added new card to arena deck: EX1_283 (2/30)
[20:22:18] : Added new card to arena deck: AT_101 (3/30)
[20:22:18] : Added new card to arena deck: CS2_189 (4/30)
[20:22:18] : Added new card to arena deck: EX1_015 (5/30)
[20:22:18] : Added new card to arena deck: CS2_029 (6/30)
[20:22:18] : Added new card to arena deck: CS2_029 (7/30)
[20:22:18] : Added new card to arena deck: FP1_001 (8/30)
[20:22:18] : Added new card to arena deck: CS2_028 (9/30)
[20:22:18] : Added new card to arena deck: EX1_019 (10/30)
[20:22:18] : Added new card to arena deck: AT_080 (11/30)
[20:22:18] : Added new card to arena deck: CS2_162 (12/30)
[20:22:18] : Added new card to arena deck: EX1_066 (13/30)
[20:22:18] : Added new card to arena deck: GVG_090 (14/30)
[20:22:18] : Added new card to arena deck: EX1_608 (15/30)
[20:22:18] : Added new card to arena deck: AT_087 (16/30)
[20:22:18] : Added new card to arena deck: FP1_001 (17/30)
[20:22:18] : Added new card to arena deck: AT_005 (18/30)
[20:22:18] : Added new card to arena deck: CS2_187 (19/30)
[20:22:18] : Added new card to arena deck: EX1_586 (20/30)
[20:22:18] : Added new card to arena deck: GVG_001 (21/30)
[20:22:18] : Added new card to arena deck: CS2_022 (22/30)
[20:22:18] : Added new card to arena deck: CS2_033 (23/30)
[20:22:18] : Added new card to arena deck: EX1_046 (24/30)
[20:22:18] : Added new card to arena deck: NEW1_023 (25/30)
[20:22:18] : Added new card to arena deck: GVG_081 (26/30)
[20:22:18] : Added new card to arena deck: CS2_155 (27/30)
[20:22:18] : Added new card to arena deck: CS2_226 (28/30)
[20:22:18] : Added new card to arena deck: BRM_002 (29/30)
[20:22:18] : Added new card to arena deck: AT_114 (30/30)
[20:22:18] : Found complete arena deck!
[20:22:18] Helper: Latest LIVE version: 0.11.3.0
[20:22:20] : ...discarded by user.
[20:22:29] PluginWrapper: Loading Arena Helper
[20:22:29] PluginWrapper: Enabled Arena Helper

**Comment by rembound** [comment]
Try deleting the Decks directory in the AppData directory of HDT. The directory is typically located at c:\Users\<username>\AppData\Roaming\HearthstoneDeckTracker\ArenaHelper

If it doesn't work, you can also delete the ArenaHelper directory from the AppData dir, but this will reset the Arena Helper settings.

**Comment by WaxPaper** [comment]
Same problem here... Tried deleting the decks folder as indicated, as well as the entire Arena Helper directory inside the app settings location; didn't help. Here's my crash log below. In the mean time not sure what to do... Might have to delete all my HDT app data, which would suck, but I love using the plugin...

-----------

########## 10/4/2015 2:11:48 AM ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at ArenaHelper.Plugin.<OnUpdate>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[2:09:49 AM] DeckList: Set active deck to: Arena 01-10 03:13 (Mage)
[2:10:06 AM] Tracker: Switched to deck: Arena 01-10 03:13
[2:10:06 AM] Game: -------- Reset ---------
[2:10:06 AM] OpponentSecrets: Cleared secrets
[2:10:13 AM] : Checking for duplicate matches...
[2:10:13 AM] GameEventHandler: Reset constructed importing
[2:10:13 AM] BackupManager: Running BackupManager
[2:10:13 AM] BackupManager: Backup for today already exists
[2:10:13 AM] PluginManager: Loading Plugins...
[2:10:13 AM] PluginWrapper: Loading Arena Helper
[2:10:13 AM] PluginWrapper: Enabled Arena Helper
[2:10:13 AM] Helper: Checking for LIVE updates...
[2:10:13 AM] Helper: Current version: 0.11.4.0
[2:10:13 AM] LogReader: Current region: US
[2:10:13 AM] UpdateOverlay: Refreshed overlay topmost status
[2:10:14 AM] Helper: Latest LIVE version: 0.11.3.0
[2:10:14 AM] Helper: Checking for BETA updates...
[2:10:14 AM] Helper: Current version: 0.11.4.0
[2:10:14 AM] Helper: Latest BETA version: 0.11.4.0
[2:10:14 AM] Game: Set CurrentGameMode to Arena
[2:10:14 AM] : Created new arena deck: Mage
[2:10:14 AM] : Added new card to arena deck: CS2_028 (1/30)
[2:10:14 AM] : Added new card to arena deck: EX1_294 (2/30)
[2:10:14 AM] : Added new card to arena deck: EX1_010 (3/30)
[2:10:14 AM] : Added new card to arena deck: CS2_188 (4/30)
[2:10:14 AM] : Added new card to arena deck: CS2_029 (5/30)
[2:10:14 AM] : Added new card to arena deck: CS2_024 (6/30)
[2:10:14 AM] : Added new card to arena deck: EX1_096 (7/30)
[2:10:14 AM] : Added new card to arena deck: CS2_022 (8/30)
[2:10:14 AM] : Added new card to arena deck: EX1_608 (9/30)
[2:10:14 AM] : Added new card to arena deck: CS2_200 (10/30)
[2:10:14 AM] : Added new card to arena deck: AT_100 (11/30)
[2:10:14 AM] : Added new card to arena deck: CS2_179 (12/30)
[2:10:14 AM] : Added new card to arena deck: GVG_065 (13/30)
[2:10:14 AM] : Added new card to arena deck: CS2_029 (14/30)
[2:10:14 AM] : Added new card to arena deck: CS2_203 (15/30)
[2:10:14 AM] : Added new card to arena deck: GVG_079 (16/30)
[2:10:14 AM] : Added new card to arena deck: BRM_024 (17/30)
[2:10:14 AM] : Added new card to arena deck: AT_101 (18/30)
[2:10:14 AM] : Added new card to arena deck: GVG_123 (19/30)
[2:10:14 AM] : Added new card to arena deck: AT_110 (20/30)
[2:10:14 AM] : Added new card to arena deck: AT_095 (21/30)
[2:10:14 AM] : Added new card to arena deck: CS2_029 (22/30)
[2:10:14 AM] : Added new card to arena deck: GVG_003 (23/30)
[2:10:14 AM] : Added new card to arena deck: AT_003 (24/30)
[2:10:14 AM] : Added new card to arena deck: GVG_001 (25/30)
[2:10:14 AM] : Added new card to arena deck: EX1_595 (26/30)
[2:10:14 AM] : Added new card to arena deck: GVG_044 (27/30)
[2:10:14 AM] : Added new card to arena deck: GVG_099 (28/30)
[2:10:14 AM] : Added new card to arena deck: EX1_595 (29/30)
[2:10:14 AM] : Added new card to arena deck: EX1_608 (30/30)
[2:10:14 AM] : Found complete arena deck!
[2:10:14 AM] : ...but we already have that one. Discarding.
[2:10:14 AM] Game: Set CurrentGameMode to Arena
[2:10:14 AM] Game: Set CurrentGameMode to Arena

**Comment by rembound** [comment]
I don't think you should have to delete all of HDT, but I don't know what causes this crash yet...

**Comment by JesseBilsten** [comment]
Crashes HDT when I open ArenaHelper

Log:
[5:44:06 PM] Game: Set CurrentGameMode to None
[5:44:06 PM] Game: -------- Reset ---------
[5:44:06 PM] OpponentSecrets: Cleared secrets
[5:44:06 PM] HearthStatsAPI: Loading stored credentials...
[5:44:06 PM] DeckList: Set active deck to: Arena 29-11 04:57 (Mage)
[5:44:08 PM] Tracker: Switched to deck: Arena 29-11 04:57
[5:44:08 PM] Game: -------- Reset ---------
[5:44:08 PM] OpponentSecrets: Cleared secrets
[5:44:08 PM] : Checking for duplicate matches...
[5:44:08 PM] GameEventHandler: Reset constructed importing
[5:44:08 PM] BackupManager: Running BackupManager
[5:44:08 PM] BackupManager: Backup for today already exists
[5:44:08 PM] PluginManager: Loading Plugins...
[5:44:08 PM] PluginWrapper: Loading Arena Helper
[5:44:08 PM] : HDTAHPluginHAPlugin constructor
[5:44:08 PM] : HearthArena cards loaded
[5:44:08 PM] : Found: HDTAHPluginHAPlugin
[5:44:08 PM] PluginWrapper: Enabled Arena Helper
[5:44:08 PM] Helper: Checking for LIVE updates...
[5:44:08 PM] Helper: Current version: 0.13.3.0
[5:44:08 PM] LogReader: Current region: US
[5:44:09 PM] UpdateOverlay: Refreshed overlay topmost status
[5:44:09 PM] Game: Set CurrentGameMode to Arena
[5:44:09 PM] : Created new arena deck: Mage
[5:44:09 PM] : Added new card to arena deck: GVG_006 (1/30)
[5:44:09 PM] : Added new card to arena deck: EX1_608 (2/30)
[5:44:09 PM] : Added new card to arena deck: EX1_294 (3/30)
[5:44:09 PM] : Added new card to arena deck: EX1_010 (4/30)
[5:44:09 PM] : Added new card to arena deck: FP1_002 (5/30)
[5:44:09 PM] : Added new card to arena deck: CS2_147 (6/30)
[5:44:09 PM] : Added new card to arena deck: NEW1_026 (7/30)
[5:44:09 PM] : Added new card to arena deck: CS2_196 (8/30)
[5:44:09 PM] : Added new card to arena deck: CS2_033 (9/30)
[5:44:09 PM] : Added new card to arena deck: AT_085 (10/30)
[5:44:09 PM] : Added new card to arena deck: AT_002 (11/30)
[5:44:09 PM] : Added new card to arena deck: EX1_028 (12/30)
[5:44:09 PM] : Added new card to arena deck: GVG_002 (13/30)
[5:44:09 PM] : Added new card to arena deck: AT_001 (14/30)
[5:44:09 PM] : Added new card to arena deck: CS2_161 (15/30)
[5:44:09 PM] : Added new card to arena deck: EX1_277 (16/30)
[5:44:09 PM] : Added new card to arena deck: GVG_001 (17/30)
[5:44:09 PM] : Added new card to arena deck: CS2_032 (18/30)
[5:44:09 PM] : Added new card to arena deck: AT_007 (19/30)
[5:44:09 PM] : Added new card to arena deck: EX1_562 (20/30)
[5:44:09 PM] : Added new card to arena deck: CS2_024 (21/30)
[5:44:09 PM] : Added new card to arena deck: LOE_029 (22/30)
[5:44:09 PM] : Added new card to arena deck: EX1_102 (23/30)
[5:44:09 PM] : Added new card to arena deck: GVG_105 (24/30)
[5:44:09 PM] : Added new card to arena deck: GVG_044 (25/30)
[5:44:09 PM] : Added new card to arena deck: CS2_186 (26/30)
[5:44:09 PM] : Added new card to arena deck: AT_090 (27/30)
[5:44:09 PM] : Added new card to arena deck: NEW1_019 (28/30)
[5:44:09 PM] : Added new card to arena deck: NEW1_023 (29/30)
[5:44:09 PM] : Added new card to arena deck: DS1_055 (30/30)
[5:44:09 PM] : Found complete arena deck!
[5:44:09 PM] : ...but we already have that one. Discarding.
[5:44:09 PM] Game: Set CurrentGameMode to Arena
[5:44:09 PM] Helper: Latest LIVE version: 0.13.3.0
[5:50:34 PM] : Resuming Arena
[5:50:34 PM] : Picked hero: Shaman, id: 7
[5:50:34 PM] : Saboteur
Loading open cv binary from C:\Program Files\Hearthstone Deck Tracker\Plugins\ArenaHelper\x86
File C:\Program Files\Hearthstone Deck Tracker\Plugins\ArenaHelper\x86\opencv_ffmpeg300.dll do not exist.

**Comment by JesseBilsten** [comment]
Looks like deleting the /decks folder cleared it up for now.

**Comment by MyopicCat** [comment]
I have the same problem, with the same missing DLL as in the log above (opencv_ffmpeg300.dll). However, deleting the /decks folder didn't work for me. When I reenabled ArenaHelper and started the plugin, the tracker immediately crashed again. Any other ideas?

**Comment by rembound** [comment]
The missing dll is normal, because it isn't needed.

I've attached a new ArenaHelper.dll that might be give more debug information in the log. Unzip it and replace the dll in `Hearthstone Deck Tracker\Plugins\ArenaHelper`

[ArenaHelper-Debug-dll.zip](https://github.com/rembound/Arena-Helper/files/66644/ArenaHelper-Debug-dll.zip)

**Comment by MyopicCat** [comment]
Tried it with the debug DLL. Same problem, HDT crashes when you select ArenaHelper from the top menu. This is the resulting log:

[15:07:08] Game: Set CurrentGameMode to None
[15:07:08] Game: -------- Reset ---------
[15:07:08] Player Name: 
[15:07:08] Opponent Name: 
[15:07:08] OpponentSecrets: Cleared secrets
[15:07:08] DeckList: Set active deck to: Arena 18-12 01:08 (Mage)
[15:07:11] Tracker: Switched to deck: Arena 18-12 01:08
[15:07:11] LogReaderManager: LogReaders could not be stopped, stop already in progress.
[15:07:11] Game: -------- Reset ---------
[15:07:11] Player Name: 
[15:07:11] Opponent Name: 
[15:07:11] OpponentSecrets: Cleared secrets
[15:07:12] : Checking for duplicate matches...
[15:07:12] GameEventHandler: Reset constructed importing
[15:07:12] BackupManager: Running BackupManager
[15:07:12] BackupManager: Backup for today already exists
[15:07:12] PluginManager: Loading Plugins...
[15:07:12] Helper: Checking for LIVE updates...
[15:07:12] Helper: Current version: 0.13.6.0
[15:07:12] LogReader: Current region: EU
[15:07:12] UpdateOverlay: Refreshed overlay topmost status
[15:07:12] Helper: Latest LIVE version: 0.13.6.0
[15:07:12] Helper: Checking for BETA updates...
[15:07:12] Helper: Current version: 0.13.6.0
[15:07:12] Helper: Latest BETA version: 0.13.5.0
[15:07:12] : Created new arena deck: Mage
[15:07:12] : Added new card to arena deck: FP1_004 (1/30)
[15:07:12] : Added new card to arena deck: GVG_081 (2/30)
[15:07:12] : Added new card to arena deck: EX1_399 (3/30)
[15:07:12] : Added new card to arena deck: EX1_275 (4/30)
[15:07:12] : Added new card to arena deck: GVG_001 (5/30)
[15:07:12] : Added new card to arena deck: CS2_022 (6/30)
[15:07:12] : Added new card to arena deck: EX1_033 (7/30)
[15:07:12] : Added new card to arena deck: FP1_001 (8/30)
[15:07:12] : Added new card to arena deck: EX1_595 (9/30)
[15:07:12] : Added new card to arena deck: GVG_006 (10/30)
[15:07:12] : Added new card to arena deck: AT_119 (11/30)
[15:07:12] : Added new card to arena deck: LOE_003 (12/30)
[15:07:12] : Added new card to arena deck: FP1_003 (13/30)
[15:07:12] : Added new card to arena deck: AT_008 (14/30)
[15:07:12] : Added new card to arena deck: GVG_096 (15/30)
[15:07:12] : Added new card to arena deck: CS2_032 (16/30)
[15:07:12] : Added new card to arena deck: CS2_028 (17/30)
[15:07:12] : Added new card to arena deck: CS2_222 (18/30)
[15:07:12] : Added new card to arena deck: CS2_032 (19/30)
[15:07:12] : Added new card to arena deck: CS2_032 (20/30)
[15:07:12] : Added new card to arena deck: tt_010 (21/30)
[15:07:12] : Added new card to arena deck: FP1_002 (22/30)
[15:07:12] : Added new card to arena deck: CS2_033 (23/30)
[15:07:12] : Added new card to arena deck: EX1_294 (24/30)
[15:07:12] : Added new card to arena deck: LOE_002 (25/30)
[15:07:12] : Added new card to arena deck: CS2_029 (26/30)
[15:07:12] : Added new card to arena deck: EX1_595 (27/30)
[15:07:12] : Added new card to arena deck: CS2_024 (28/30)
[15:07:12] : Added new card to arena deck: GVG_078 (29/30)
[15:07:12] : Added new card to arena deck: BRM_022 (30/30)
[15:07:12] : Found complete arena deck!
[15:07:12] : ...but we already have that one. Discarding.
[15:07:12] Game: Set CurrentGameMode to Arena
[15:07:20] PluginWrapper: Loading Arena Helper
[15:07:20] PluginWrapper: Enabled Arena Helper
Loading open cv binary from C:\Program Files (x86)\Hearthstone Deck Tracker\Plugins\ArenaHelper\x86
File C:\Program Files (x86)\Hearthstone Deck Tracker\Plugins\ArenaHelper\x86\opencv_ffmpeg300.dll do not exist.

**Comment by rembound** [comment]
Just to exclude it, try to add the opencv_ffmpeg300.dll. I've attached a zip with the file.
It should be placed at `Hearthstone Deck Tracker\Plugins\ArenaHelper\x86`
[opencv_ffmpeg300.zip](https://github.com/rembound/Arena-Helper/files/66795/opencv_ffmpeg300.zip)

I've also added more debug messages:
[ArenaHelper-Debug-dll.v2.zip](https://github.com/rembound/Arena-Helper/files/66814/ArenaHelper-Debug-dll.v2.zip)

**Comment by MyopicCat** [comment]
OK, tried it with the ffmpeg DLL and the new debug DLL. Same crash. I don't see anything helpful in the log, but maybe you see something I don't.

[14:51:48] Game: Set CurrentGameMode to None
[14:51:48] Game: -------- Reset ---------
[14:51:48] Player Name: 
[14:51:48] Opponent Name: 
[14:51:48] OpponentSecrets: Cleared secrets
[14:51:48] DeckList: Set active deck to: Murloc OTK (Paladin)
[14:51:51] Tracker: Switched to deck: Murloc OTK
[14:51:51] LogReaderManager: LogReaders could not be stopped, stop already in progress.
[14:51:51] Game: -------- Reset ---------
[14:51:51] Player Name: 
[14:51:51] Opponent Name: 
[14:51:51] OpponentSecrets: Cleared secrets
[14:51:51] : Checking for duplicate matches...
[14:51:51] GameEventHandler: Reset constructed importing
[14:51:51] BackupManager: Running BackupManager
[14:51:51] BackupManager: Deleting old backup: Backup_03122015.zip
[14:51:51] BackupManager: Backup for today already exists
[14:51:51] PluginManager: Loading Plugins...
[14:51:51] Helper: Checking for LIVE updates...
[14:51:51] Helper: Current version: 0.13.7.0
[14:51:51] Helper: Latest LIVE version: 0.13.7.0
[14:51:51] Helper: Checking for BETA updates...
[14:51:51] Helper: Current version: 0.13.7.0
[14:51:51] Helper: Latest BETA version: 0.13.5.0
[14:52:25] Tracker: Switched to deck: Totem 1.0
[14:52:25] DeckList: Set active deck to: Totem 1.0 (Shaman)
[14:52:25] LogReaderManager: Stopped LogReaders.
[14:52:25] Game: -------- Reset ---------
[14:52:25] Player Name: 
[14:52:25] Opponent Name: 
[14:52:25] OpponentSecrets: Cleared secrets
[14:52:25] LogReaderManager: Restarting LogReaders.
[14:52:30] PluginWrapper: Loading Arena Helper
[14:52:30] PluginWrapper: Enabled Arena Helper

**Comment by rembound** [comment]
No new messages probably means that the crash doesn't occur in the tested code. Maybe some dll or library is incompatible with your system. I can't solve the problem at this point.

**Comment by Tachyon2032** [comment]
Having the same issue.  Wanted to throw this out there: I moved my HDT installation (and therefore ArenaHelper, too) to a different drive and directory: D:\Program Files (x86)\Hearthstone Deck Tracker\Plugins.  Anyone else crashing with similar install location?

**Comment by waldohs** [comment]
Not sure if this will apply to everybody, but I managed to get this working. When I originally downloaded the plugin I didn't have a Plugins folder in my Hearthstone Deck Tracker folder. So I created one and put Arena Helper in there. Arena Helper would crash as soon as it was launched, same as reported here.

What I did to fix it was to delete the Plugins folder, redownload HDT and copy the Plugins folder from the new download to the old install. Then add Arena Helper in to that folder. I'm assuming it was probably some sort of permissions issue, though I didn't keep the old folder around so I can't compare.

**Comment by MyopicCat** [comment]
Thanks a lot ghost, that finally solved it for me as well!

**Comment by Tachyon2032** [comment]
I tried this and it did not resolve the issue for me.  In fact, the first time I tried to run Arena Helper, it gave me two errors (crash report attached).  Tried it again and only got single error second time.  Thanks for any help anyone can share; holding off playing Arena until I get this resolved.
[Crash report 2012016-046.txt](https://github.com/rembound/Arena-Helper/files/97044/Crash.report.2012016-046.txt)

**Comment by rembound** [comment]
@Tachyon2032 Open up %appdata% in windows explorer and go to the `HearthstoneDeckTracker\ArenaHelper\` directory. Delete the `Decks` directory to solve the LoadArenaData problem.

**Comment by Tachyon2032** [comment]
Deleting the Decks directory did the trick.  Thanks!

**Comment by rembound** [comment]
I've released [Arena Helper v0.6.5](https://github.com/rembound/Arena-Helper/releases) which uses the AppData directory for downloaded data files. This should solve permission issues. It doesn't solve corrupted config/deck files though.
