### ISSUE TITLE
System.NullReferenceException at ArenaHelper.Plugin.LoadConfig()

### ISSUE THREAD

**Issue by Epix37** [rembound/Arena-Helper#62]
There seems to be some issue where the Plugin causes HDT to crash (repeatedly).

Log:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ArenaHelper.Plugin.<OnUpdate>d__c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[2:59:51 PM] DeckList: Set active deck to: Arena 21-01 03:23 (Mage)
[2:59:52 PM] Tracker: Switched to deck: Arena 21-01 03:23
[2:59:52 PM] LogReaderManager: LogReaders could not be stopped, stop already in progress.
[2:59:52 PM] Game: -------- Reset ---------
[2:59:52 PM] Player Name: 
[2:59:52 PM] Opponent Name: 
[2:59:52 PM] OpponentSecrets: Cleared secrets
[2:59:53 PM] : Checking for duplicate matches...
[2:59:53 PM] GameEventHandler: Reset constructed importing
[2:59:53 PM] BackupManager: Running BackupManager
[2:59:53 PM] BackupManager: Backup for today already exists
[2:59:53 PM] PluginManager: Loading Plugins...
[2:59:53 PM] Helper: Checking for LIVE updates...
[2:59:53 PM] Helper: Current version: 0.13.7.0
[2:59:53 PM] Helper: Latest LIVE version: 0.13.7.0
[3:00:02 PM] PluginWrapper: Loading Arena Helper
[3:00:02 PM] PluginWrapper: Enabled Arena Helper
[3:00:06 PM] PluginWrapper: Error performing OnButtonPress for Arena Helper:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ArenaHelper.Plugin.LoadConfig()
   at ArenaHelper.Plugin.InitializeMainWindow()
   at ArenaHelper.Plugin.ActivateArenaWindow()
   at ArenaHelper.Plugin.OnButtonPress()
   at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.OnButtonPress()
```

See here for more information https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/2030

**Comment by rembound** [comment]
Made a comment at https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/2030
See also issue #33

**Comment by rembound** [comment]
If anyone else has this problem, please zip the ArenaHelper directory from appdata and attach it to a reply, so I can reproduce this error.

> Open up %appdata% in windows explorer and go to the `HearthstoneDeckTracker\ArenaHelper\`

**Comment by Sombres** [comment]
Here you go. In my case, deleting the Decks folder solved the problem.
[ArenaHelper.zip](https://github.com/rembound/Arena-Helper/files/124859/ArenaHelper.zip)

**Comment by rembound** [comment]
Thanks, I can see that the last file `Arena-20160208-1307.json` of the decks folder is corrupt. It only contains zeroes. You could copy the other files back if you want.

**Comment by rembound** [comment]
Added better file corruption handling in [Arena Helper v0.6.6](https://github.com/rembound/Arena-Helper/releases).
