### ISSUE TITLE
NullReferenceException at ArenaHelper.Plugin.LoadArenaData(String filename)

### ISSUE THREAD

**Issue by Epix37** [rembound/Arena-Helper#63]
Got another one.

> [...] as soon as I try to launch the arena tracker plugin, it crashes [...] already tried deleting and reinstalling the plugin

Log:
```
########## 1/30/2016 5:52:17 PM ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at ArenaHelper.Plugin.LoadArenaData(String filename)
   at ArenaHelper.Plugin.InitializeMainWindow()
   at ArenaHelper.Plugin.ActivateArenaWindow()
   at ArenaHelper.Plugin.<AddMenuItem>b__1(Object sender, RoutedEventArgs args)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[5:51:57 PM] LogReaderManager: LogReaders could not be stopped, stop already in progress.
[5:51:57 PM] Game: -------- Reset ---------
[5:51:57 PM] Player Name: 
[5:51:57 PM] Opponent Name: 
[5:51:57 PM] OpponentSecrets: Cleared secrets
[5:51:58 PM] : Checking for duplicate matches...
[5:51:58 PM] GameEventHandler: Reset constructed importing
[5:51:58 PM] BackupManager: Running BackupManager
[5:51:58 PM] BackupManager: Backup for today already exists
[5:51:58 PM] PluginManager: Loading Plugins...
[5:51:58 PM] PluginWrapper: Loading Collection Tracker
[5:51:58 PM] PluginWrapper: Enabled Collection Tracker
[5:51:58 PM] PluginWrapper: Loading Arena Helper
[5:51:58 PM] PluginWrapper: Enabled Arena Helper
[5:51:58 PM] Helper: Checking for LIVE updates...
[5:51:58 PM] Helper: Current version: 0.13.9.0
[5:51:59 PM] Helper: Latest LIVE version: 0.13.9.0
```

**Comment by rembound** [comment]
See issue #62

**Comment by rembound** [comment]
Added better file corruption handling in [Arena Helper v0.6.6](https://github.com/rembound/Arena-Helper/releases).
